# =====================================================================
# make/help.mk — Meta-comandos (help, etc.)
# =====================================================================

.PHONY: help
help: ## Mostra esta ajuda
	$(call print_help)

# Função para imprimir ajuda organizada
define print_help
	@echo ""
	@echo "====================================================="
	@echo "  ${BOLD}pos-uncisal-projeto-aplicado${RESET} — Comandos Makefile"
	@echo "====================================================="
	@echo ""
	@echo "  ${YELLOW}Desenvolvimento Local:${RESET}"
	@echo "    ${GREEN}setup${RESET}                  - Cria ambiente virtual, instala dependências"
	@echo "    ${GREEN}run${RESET}                    - Sobe servidor Django local"
	@echo "    ${GREEN}test${RESET}                   - Roda testes unitários"
	@echo "    ${GREEN}check${RESET}                  - Verifica configurações Django"
	@echo "    ${GREEN}secret-key${RESET}             - Gera nova SECRET_KEY"
	@echo "    ${GREEN}certs${RESET}                  - Gera certificados TLS autoassinados"
	@echo ""
	@echo "  ${YELLOW}Docker + Nginx (HTTPS):${RESET}"
	@echo "    ${GREEN}up${RESET}                     - Sobe stack Docker (foreground)"
	@echo "    ${GREEN}up-d${RESET}                   - Sobe stack Docker (background)"
	@echo "    ${GREEN}down${RESET}                  - Para containers"
	@echo "    ${GREEN}down-v${RESET}                - Para containers e remove volumes"
	@echo "    ${GREEN}build${RESET}                 - Build das imagens Docker"
	@echo "    ${GREEN}logs${RESET}                  - Mostra logs dos containers"
	@echo "    ${GREEN}ps${RESET}                    - Status dos containers"
	@echo "    ${GREEN}docker-test${RESET}            - Testes dentro dos containers"
	@echo "    ${GREEN}docker-shell${RESET}           - Shell no container web"
	@echo ""
	@echo "  ${YELLOW}Vagrant (Testes Locais):${RESET}"
	@echo "    ${GREEN}vagrant-up${RESET}             - Inicia VM Vagrant"
	@echo "    ${GREEN}vagrant-up-clean${RESET}       - Destrói e recria VM"
	@echo "    ${GREEN}vagrant-halt${RESET}           - Para a VM"
	@echo "    ${GREEN}vagrant-suspend${RESET}        - Suspende a VM"
	@echo "    ${GREEN}vagrant-resume${RESET}         - Retoma a VM suspensa"
	@echo "    ${GREEN}vagrant-destroy${RESET}        - Destrói a VM"
	@echo "    ${GREEN}vagrant-status${RESET}        - Status da VM"
	@echo "    ${GREEN}vagrant-ssh${RESET}            - SSH para dentro da VM"
	@echo "    ${GREEN}vagrant-access${RESET}        - Mostra URLs de acesso"
	@echo "    ${GREEN}vagrant-logs${RESET}          - Mostra logs do provisionamento"
	@echo "    ${GREEN}vagrant-docker-logs${RESET}   - Logs dos containers na VM"
	@echo "    ${GREEN}vagrant-docker-test${RESET}   - Testes Django dentro da VM"
	@echo "    ${GREEN}vagrant-clean${RESET}         - Limpa arquivos temporários"
	@echo "    ${GREEN}vagrant-check${RESET}         - Verifica pré-requisitos"
	@echo ""
	@echo "  ${YELLOW}Testes Multi-Ambiente:${RESET}"
	@echo "    ${GREEN}test-all${RESET}               - Testes em todos ambientes disponíveis"
	@echo "    ${GREEN}test-matrix${RESET}           - Testes em matriz: local, Docker, Vagrant"
	@echo ""
	@echo "  ${YELLOW}Terraform OCI (Oracle Cloud):${RESET}"
	@echo "    ${GREEN}terraform-hmg-plan${RESET}     - Plano de execução (homologação)"
	@echo "    ${GREEN}terraform-hmg-apply${RESET}    - Aplica configuração (homologação)"
	@echo "    ${GREEN}terraform-hmg-destroy${RESET}  - Destrói recursos (homologação)"
	@echo "    ${GREEN}terraform-hmg-output${RESET}  - Mostra outputs (homologação)"
	@echo "    ${GREEN}terraform-hmg-ssh${RESET}     - SSH para instância (homologação)"
	@echo "    ${GREEN}terraform-hmg-logs${RESET}    - Logs da aplicação (homologação)"
	@echo "    ${GREEN}terraform-hmg-test${RESET}    - Testes Django na VM (homologação)"
	@echo "    ${GREEN}terraform-prd-plan${RESET}    - Plano de execução (produção)"
	@echo "    ${GREEN}terraform-prd-apply${RESET}   - Aplica configuração (produção)"
	@echo "    ${GREEN}terraform-prd-destroy${RESET} - Destrói recursos (produção)"
	@echo "    ${GREEN}terraform-prd-output${RESET}   - Mostra outputs (produção)"
	@echo "    ${GREEN}terraform-prd-ssh${RESET}      - SSH para instância (produção)"
	@echo "    ${GREEN}terraform-prd-logs${RESET}    - Logs da aplicação (produção)"
	@echo "    ${GREEN}terraform-prd-test${RESET}    - Testes Django na VM (produção)"
	@echo ""
	@echo "  ${YELLOW}Segurança e verificação de segredos:${RESET}"
	@echo "    ${GREEN}install-gitleaks${RESET}      - Instala o gitleaks para detecção de segredos"
	@echo "    ${GREEN}gitleaks-detect${RESET}       - Verifica segredos no histórico do repositório"
	@echo "    ${GREEN}gitleaks-protect${RESET}      - Verifica segredos nos arquivos staged (pré-commit)"
	@echo "    ${GREEN}gitleaks-test${RESET}         - Testa os hooks de verificação de segredos"
	@echo "    ${GREEN}security-check${RESET}        - Verificação completa de segurança"
	@echo ""
	@echo "  ${YELLOW}Limpeza e Manutenção:${RESET}"
	@echo "    ${GREEN}clean${RESET}                 - Limpa caches e arquivos temporários"
	@echo "    ${GREEN}clean-all${RESET}             - Limpa tudo (incluindo .venv e volumes)"
	@echo "    ${GREEN}clean-pyc${RESET}            - Remove arquivos Python compilados"
	@echo "    ${GREEN}clean-docker${RESET}         - Limpeza Docker (containers parados, imagens não usadas)"
	@echo ""
	@echo "  ${YELLOW}Utilitários:${RESET}"
	@echo "    ${GREEN}help${RESET}                  - Mostra esta ajuda"
	@echo "    ${GREEN}version${RESET}               - Mostra versões dos componentes"
	@echo ""
	@echo "====================================================="
	@echo "  ${BOLD}Dica:${RESET} Use 'make <alvo> ARG=valor' para passar parâmetros"
	@echo "  ${BOLD}Aviso:${RESET} make down-v e make clean-all são destrutivos!"
	@echo "====================================================="
	@echo ""
endef